import { StyleSheet } from 'react-native';

export const COLORS = {
  bg: '#1b0b18',
  bgAlt: '#261022',
  card: '#2f152a',
  primary: '#ff8fb1',
  primaryDark: '#e8759b',
  text: '#fef3f7',
  subtext: '#f4c8d9',
  yes: '#ff9ec7',
  no: '#f76480',
  maybe: '#ffc094',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    justifyContent: 'center',

  },
  // Centers inner content and adds left/right space on wide screens
  content: {
    width: '100%',

    alignSelf: 'center',
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    alignItems: 'center',
    paddingTop: 40,
    paddingHorizontal: 24,
  },
  logo: {
    width: 96,
    height: 96,
    borderRadius: 20,
    marginBottom: 16,
  },
  title: {
    color: COLORS.text,
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 1,
  },
  subtitle: {
    color: COLORS.subtext,
    fontSize: 17,
    marginTop: 8,
  },
  actions: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  screenPad: {
    flex: 1,
    paddingVertical: 24,
    width: '100%',
    maxWidth: 860,
    alignSelf: 'center',
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    borderRadius: 14,
    paddingVertical: 16,
    padding: 16,
    marginBottom: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  buttonPrimary: {
    backgroundColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonPrimaryText: {
    color: '#1b0b18',
    fontSize: 18,
    fontWeight: '800',
  },
  headerSmall: {
    marginBottom: 18,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  badge: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
  },
  badgeYes: {
    borderWidth: 1,
    borderColor: COLORS.yes,
  },
  badgeMaybe: {
    borderWidth: 1,
    borderColor: COLORS.maybe,
  },
  badgeNo: {
    borderWidth: 1,
    borderColor: COLORS.no,
  },
  badgeText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '600',
  },
  footer: {
    marginTop: 'auto',
    padding: 24,
    alignItems: 'center',
  },
  footerText: {
    color: COLORS.subtext,
  },
  input: {
    backgroundColor: COLORS.bgAlt,
    color: COLORS.text,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
  },
  qCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  qLabel: {
    color: COLORS.text,
    fontSize: 18,
    marginBottom: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  qOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionHeader: {
    paddingTop: 12,
    paddingBottom: 6,
  },
  sectionTitle: {
    color: COLORS.subtext,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  optBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.subtext,
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: 'center',
    marginHorizontal: 4,
    backgroundColor: COLORS.bgAlt,
  },
  optBtnActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primaryDark,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  optText: {
    color: COLORS.text,
    fontWeight: '700',
  },
  optTextActive: {
    color: COLORS.bg,
    fontWeight: '800',
  },
  matchItem: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  matchText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '600',
  },
  choicesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  pill: {
    borderWidth: 1,
    borderColor: COLORS.subtext,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginRight: 8,
    marginBottom: 6,
    backgroundColor: 'transparent',
  },
  pillText: {
    color: COLORS.subtext,
    fontWeight: '600',
    fontSize: 12,
  },
});
